// Package simplemessage is a vendor-agnostic messaging/OTP delivery wrapper.
// It exposes a master-set Provider interface; implementations that cannot
// perform an operation return ErrNotSupported ("not applicable").
//
// Capabilities span email (SMTP), WhatsApp (Meta Cloud API), SMS + WhatsApp
// (Indonesian vendors) and Telegram. SendOTP is the primary use case today;
// SendMessage covers confirmations, registration links, welcome messages, etc.
//
// OTP codes are ALWAYS generated with goutil/encryption (GenerateOTP /
// GenerateSecureRandomNumber / GenerateDefaultOTP) — never reimplemented.
// See otp.go and DESCRIPTION.md.
package simplemessage

import (
	"context"
	"errors"
	"net/http"
	"time"
)

// Channel is the delivery channel a message is sent over.
type Channel string

const (
	ChannelEmail    Channel = "email"
	ChannelWhatsApp Channel = "whatsapp"
	ChannelSMS      Channel = "sms"
	ChannelTelegram Channel = "telegram"
)

// MessageType classifies the purpose of a message.
type MessageType string

const (
	MessageTypeOTP          MessageType = "otp"
	MessageTypeVerification MessageType = "verification"
	MessageTypeWelcome      MessageType = "welcome"
	MessageTypeNotification MessageType = "notification"
)

// ErrNotSupported is returned by an implementation for a master-set operation
// the underlying channel/vendor does not provide.
var ErrNotSupported = errors.New("simplemessage: operation not supported by this provider")

// SendRequest is the normalized send request understood by every provider.
type SendRequest struct {
	To      string // recipient: email address, phone number (+62812...), telegram chat id
	Channel Channel

	MessageType MessageType
	Subject     string            // email subject / message title
	Body        string            // plain-text body; "{code}" is replaced with the OTP when present
	TemplateName   string         // vendor template name (WhatsApp); Body used when empty
	TemplateParams map[string]string

	// OTP controls. When Code is empty, the library generates one using
	// goutil/encryption (see otp.go).
	Code       string
	CodeLength int
	ExpiresIn  time.Duration // informational validity window (caller enforces TTL)

	Metadata map[string]string
}

// SendResponse is the normalized result of a send.
type SendResponse struct {
	MessageID string
	Status    string // sent | queued | failed
	Channel   Channel
	// CostCents is the vendor-reported cost in smallest unit of Currency
	// (USD cents / IDR rupiah). 0 when the vendor does not report costs —
	// the consuming app applies its own rate table for metering.
	CostCents int64
	Currency  string
	// Code is the OTP code sent (generated by goutil when the request did
	// not carry one). Callers that verify codes store it server-side.
	Code string
}

// MessageStatus is a normalized delivery status snapshot.
type MessageStatus struct {
	MessageID string
	Status    string // sent | delivered | read | failed
}

// BalanceResponse is a normalized account balance snapshot (mainly Indonesian
// SMS/WA vendors); ErrNotSupported elsewhere.
type BalanceResponse struct {
	Balance int64
	Currency string
	Raw      map[string]interface{}
}

// WebhookEvent is a normalized delivery/status webhook event.
type WebhookEvent struct {
	Type string                 // e.g. "message.status", "message.received"
	ID   string                 // message/update id when known
	Data map[string]interface{} // raw payload
	Raw  []byte                 // original request body
}

// Provider is the master-set messaging interface.
type Provider interface {
	// Name returns the provider key ("email", "whatsapp", "sms", "telegram").
	Name() string

	// Send delivers a message (OTP, verification, welcome, notification...).
	Send(ctx context.Context, req *SendRequest) (*SendResponse, error)

	// GetStatus retrieves delivery status (ErrNotSupported where N/A).
	GetStatus(ctx context.Context, messageID string) (*MessageStatus, error)

	// GetBalance retrieves the vendor account balance (ErrNotSupported where N/A).
	GetBalance(ctx context.Context) (*BalanceResponse, error)

	// VerifyWebhook authenticates and parses a vendor webhook payload.
	VerifyWebhook(body []byte, headers http.Header) (*WebhookEvent, error)
}
